#!/bin/bash

declare  a=2
declare  b=4
declare   c=7

for ((i=1; i<=20; i++ ));do
a=$((a*i))
b=$((b + a + i))
c=$((c + (a -i)))
echo "a=$a, b=$b, c=$c"
if (( a % 2 == 0 && b % 2 == 0 && c % 2 == 0)); then 
echo "zmienne sa parzyste"
fi 
done

