#!/bin/bash 
declare -a t=(5 6 3 4 7)
i=0 
k=${#t[@]}
for ((i=0; i<k-1; i++));do
for ((j=0; j<k-i-1;j++));do
echo ${t[@]}
if ((${t[j]}> ${t[j+1]}));then
a=${t[j]}
t[j]=${t[j+1]}
t[j+1]=$a
fi
done
done
echo " koncowa tablica po sortowaniu to:" ${t[@]}
